<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(WindowsTfm)</TargetFramework>
    <RootNamespace>PhotoGallery.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MetadataExtractor" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Identity.Client" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PhotoGallery.Core.Tests" />
  </ItemGroup>
</Project>
