<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="Microsoft.Graphics.Win2D" Version="1.4.0" />
    <PackageVersion Include="MetadataExtractor" Version="2.9.3" />
    <PackageVersion Include="Dapper" Version="2.1.89" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Identity.Client" Version="4.90.0" />
    <PackageVersion Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.90.0" />
    <PackageVersion Include="Whisper.net" Version="1.9.1" />
    <PackageVersion Include="Whisper.net.Runtime" Version="1.9.1" />
    <PackageVersion Include="Whisper.net.Runtime.Vulkan" Version="1.9.1" />
    <PackageVersion Include="org.k2fsa.sherpa.onnx" Version="1.13.8" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
  </ItemGroup>
</Project>
