<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(WindowsTfm)</TargetFramework>
    <RootNamespace>PhotoGallery.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\PhotoGallery.Core\PhotoGallery.Core.csproj" />
  </ItemGroup>
</Project>
